"""NPZ-based map pool for neural-belief training.

Maps are generated by ``generate_training_maps.py`` and stored in an npz pool
directory.  This module provides read-only access to that pool.

Directory layout
----------------
    <pool_dir>/
        config.pkl              dataset config written by the generation script
        map_00000.npz           per-map arrays (see below)
        map_00001.npz
        ...

Per-map npz keys
----------------
    boreholes     : (n_boreholes, V, D) float32 — raw (unstandardised) variables
    yield_target  : (n_x, n_y)         float32 — max-pooled yield field
    drill_locs    : (S, max_drills, 2) int16   — drill locations per sample
    drill_ore_vals: (S, max_drills)    float32 — ore values at drill locations
    drill_counts  : (S,)               int16   — valid drills per sample
    where S = samples_per_map
"""

from __future__ import annotations

import dataclasses
import pickle
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch

from .datasets import BeliefDatasetConfig, GeologicalBeliefDataset
from .models.borehole_encoders.autoencoder import standardise
from decision_simulator.resources import DecisionSimulationResources

# Drill pattern helper
# ---------------------------------------------------------------------------

_DEFAULT_PREFIX_STEPS = [1, 2, 3, 5, 8, 10, 15]


def _unpack_drill_patterns(
    locs: np.ndarray,
    vals: np.ndarray,
    counts: np.ndarray,
) -> list[tuple[list[tuple[int, int]], list[float]]]:
    samples = []
    for i, k in enumerate(counts):
        drill_locs = [(int(locs[i, j, 0]), int(locs[i, j, 1])) for j in range(k)]
        ore_vals = [float(vals[i, j]) for j in range(k)]
        samples.append((drill_locs, ore_vals))
    return samples


# ---------------------------------------------------------------------------
# Layer 1: In-memory container
# ---------------------------------------------------------------------------


@dataclass
class NpzMap:
    """In-memory container for map pool data loaded from an npz cache.

    Created by :meth:`NpzMapCacheStore.load_subset`.
    """

    borehole_arrays: list[np.ndarray]  # each (n_boreholes, V, D) float32, raw
    targets: list[np.ndarray]  # each (n_x, n_y) float32
    drill_patterns: list[list[tuple[list[tuple[int, int]], list[float]]]]
    cfg: BeliefDatasetConfig
    n_x: int
    n_y: int

    @property
    def pool_size(self) -> int:
        return len(self.borehole_arrays)

    def encode_full_latent_map(
        self,
        borehole_array: np.ndarray,
        resources: DecisionSimulationResources,
        device: str,
        batch_size: int = 256,
    ) -> np.ndarray:
        """Encode every borehole in a map in one batched pass.

        Parameters
        ----------
        borehole_array
            Pre-computed borehole tensor of shape ``(n_x * n_y, V, D)`` float32.
            Must already be standardised and nan-zeroed before calling.
        resources
            Shared experiment resources; encoder is resolved as:
            1. ``resources.borehole_encoder_fn`` if set
            2. ``resources.jepa_model.embed`` as fallback
            3. Neither set → returns empty ``(n_x, n_y, 0)`` array (no-encoder mode)
        device
            Torch device string.
        batch_size
            Boreholes encoded per forward pass.

        Returns
        -------
        np.ndarray of shape ``(n_x, n_y, latent_dim)`` float32
        """
        encoder_fn = getattr(resources, "borehole_encoder_fn", None)
        if encoder_fn is None:
            jepa = getattr(resources, "jepa_model", None)
            if jepa is not None:
                encoder_fn = jepa.embed

        if encoder_fn is None:
            return np.zeros((self.n_x, self.n_y, 0), dtype=np.float32)

        bh_tensor = torch.from_numpy(borehole_array.astype(np.float32)).to(device)

        chunks: list[np.ndarray] = []
        for start in range(0, bh_tensor.shape[0], batch_size):
            with torch.no_grad():
                lat = encoder_fn(bh_tensor[start : start + batch_size])
            chunks.append(lat.cpu().numpy())

        latents = np.concatenate(chunks, axis=0)  # (n_x*n_y, latent_dim)
        return latents.reshape(self.n_x, self.n_y, -1).astype(np.float32)

    @staticmethod
    def build_sample_input(
        drill_locations: list[tuple[int, int]],
        ore_values: list[float],
        full_latent_map: np.ndarray,  # (n_x, n_y, latent_dim)
    ) -> np.ndarray:
        """Construct the ``(2 + latent_dim, n_x, n_y)`` model input from a drill pattern.

        Channel layout
        --------------
        [0]       : sparse observed ore map  (0 at unobserved cells)
        [1]       : binary observation mask  (1 = observed, 0 = unobserved)
        [2 ...]   : JEPA latent vectors      (zero vector at unobserved cells)
        """
        n_x, n_y, latent_dim = full_latent_map.shape

        sparse_ore = np.zeros((n_x, n_y), dtype=np.float32)
        mask = np.zeros((n_x, n_y), dtype=np.float32)
        jepa_map = np.zeros((n_x, n_y, latent_dim), dtype=np.float32)

        for (i, j), ore_val in zip(drill_locations, ore_values):
            sparse_ore[i, j] = float(ore_val)
            mask[i, j] = 1.0
            jepa_map[i, j] = full_latent_map[i, j]

        return np.concatenate(
            [
                sparse_ore[np.newaxis],          # (1, n_x, n_y)
                mask[np.newaxis],                # (1, n_x, n_y)
                jepa_map.transpose(2, 0, 1),     # (latent_dim, n_x, n_y)
            ],
            axis=0,
        )  # (2 + latent_dim, n_x, n_y)

    def build_geo_train_maps(
        self,
        resources: DecisionSimulationResources,
        device: str,
        n_sequences_per_map: int = 1,
        max_drills: int = 15,
        prefix_steps: list[int] | None = None,
        seed: int = 42,
        verbose: bool = False,
        shuffle_latents: bool = False,
        shuffle_seed: int = 0,
    ) -> GeologicalBeliefDataset:
        """Build a sequential prefix dataset from this map cache.

        For each map, generates ``n_sequences_per_map`` random drill orderings.
        Each ordering produces one sample per checkpoint in ``prefix_steps``,
        where step *k* reveals the first *k* drills of the sequence.

        All prefixes from the same map are always in the same train/val split
        (guaranteed by the map-level split in ``NpzMapCacheStore``).

        Parameters
        ----------
        resources
            Encoder model + normalisation stats.
        device
            Torch device for encoder forward passes.
        n_sequences_per_map
            Number of independent drill orderings per map.  More orderings reduce
            memorisation of a single exploration path.
        max_drills
            Length of each generated sequence.  ``prefix_steps`` values above this
            are clamped to ``max_drills``.
        prefix_steps
            Drill-count checkpoints at which to create samples.
            Defaults to ``[1, 2, 3, 5, 8, 10, 15]``.
        seed
            Master RNG seed.  Each (map, sequence) pair gets a deterministic
            sub-seed so the dataset is fully reproducible.
        verbose
            Print progress every 10 maps.
        shuffle_latents
            Spatially scramble latent vectors (control variant).
        shuffle_seed
            Base seed for per-map latent shuffle.

        Returns
        -------
        GeologicalBeliefDataset
            Dataset with ``metadata`` list containing ``map_id``, ``sequence_id``,
            ``step``, and ``n_drills`` per sample.
        """
        if prefix_steps is None:
            prefix_steps = _DEFAULT_PREFIX_STEPS

        n_x, n_y = self.n_x, self.n_y
        all_locs = [(i, j) for i in range(n_x) for j in range(n_y)]

        all_inputs: list[np.ndarray] = []
        all_targets: list[np.ndarray] = []
        metadata_list: list[dict] = []
        drill_count_list: list[int] = []

        for map_idx, (bh_arr, target_ore) in enumerate(
            zip(self.borehole_arrays, self.targets)
        ):
            bh_std = bh_arr.astype(np.float32)
            if resources.norm_stats and resources.variable_names:
                bh_std = standardise(
                    bh_std, resources.norm_stats, resources.variable_names
                )
                bh_std = np.nan_to_num(bh_std, nan=0.0)

            full_latent_map = self.encode_full_latent_map(bh_std, resources, device)

            if shuffle_latents and full_latent_map.shape[2] > 0:
                flat = full_latent_map.reshape(-1, full_latent_map.shape[2])
                np.random.default_rng(shuffle_seed + map_idx).shuffle(flat)
                full_latent_map = flat.reshape(n_x, n_y, -1)

            for seq_id in range(n_sequences_per_map):
                seq_seed = seed + map_idx * n_sequences_per_map + seq_id
                perm = np.random.default_rng(seq_seed).permutation(len(all_locs))
                sequence_locs = [all_locs[k] for k in perm[:max_drills]]

                for step in prefix_steps:
                    actual_step = min(step, len(sequence_locs))
                    drill_locs = sequence_locs[:actual_step]
                    ore_vals = [float(target_ore[i, j]) for i, j in drill_locs]

                    inp = NpzMap.build_sample_input(drill_locs, ore_vals, full_latent_map)
                    all_inputs.append(inp)
                    all_targets.append(target_ore[np.newaxis])  # (1, n_x, n_y)
                    metadata_list.append(
                        {
                            "map_id": map_idx,
                            "sequence_id": seq_id,
                            "step": actual_step,
                            "n_drills": actual_step,
                        }
                    )
                    drill_count_list.append(actual_step)

            if verbose and (map_idx + 1) % 10 == 0:
                print(
                    f"  [encode] {map_idx + 1}/{len(self.borehole_arrays)} maps encoded"
                )

        inputs_t = torch.from_numpy(np.stack(all_inputs))
        targets_t = torch.from_numpy(np.stack(all_targets))
        drill_counts_t = torch.tensor(drill_count_list, dtype=torch.long)
        return GeologicalBeliefDataset(
            inputs_t,
            targets_t,
            drill_counts=drill_counts_t,
            metadata=metadata_list,
        )


# ---------------------------------------------------------------------------
# Layer 2: NPZ persistence
# ---------------------------------------------------------------------------


class NpzMapCacheStore:
    """NPZ directory persistence for raw belief map pools.

    Each map is stored as a compressed npz file.  Global metadata
    (config) lives in the same directory.

    Parameters
    ----------
    path
        Directory that holds the pool files.
    """

    def __init__(self, path: Path | str) -> None:
        self.path = Path(path)

    def _map_path(self, idx: int) -> Path:
        return self.path / f"map_{idx:05d}.npz"

    def _config_path(self) -> Path:
        return self.path / "config.pkl"

    def count_maps(self) -> int:
        """Return the number of map files present on disk."""
        if not self.path.exists():
            return 0
        return sum(1 for p in self.path.glob("map_*.npz") if p.is_file())

    def load_subset(self, indices: list[int]) -> NpzMap:
        """Load the maps at *indices* and return an in-memory :class:`NpzMap`."""
        with open(self._config_path(), "rb") as f:
            meta = pickle.load(f)
        n_x: int = meta["n_x"]
        n_y: int = meta["n_y"]
        stored_cfg = BeliefDatasetConfig(
            n_maps=meta["n_maps"],
            samples_per_map=meta["samples_per_map"],
            min_drills=meta["min_drills"],
            max_drills=meta["max_drills"],
            seed=meta["seed"],
        )

        borehole_arrays, targets, drill_patterns = [], [], []
        for idx in indices:
            data = np.load(self._map_path(idx))
            borehole_arrays.append(data["boreholes"])
            targets.append(data["yield_target"])
            drill_patterns.append(
                _unpack_drill_patterns(
                    data["drill_locs"],
                    data["drill_ore_vals"],
                    data["drill_counts"],
                )
            )

        return NpzMap(
            borehole_arrays=borehole_arrays,
            targets=targets,
            drill_patterns=drill_patterns,
            cfg=dataclasses.replace(stored_cfg, n_maps=len(indices)),
            n_x=n_x,
            n_y=n_y,
        )

    def load_map_data(
        self,
        n_train_maps: int,
        n_val_maps: int,
        n_orebodies: int,
        seed: int = 42,
    ) -> tuple[NpzMap, NpzMap]:
        """Load train/val subsets stratified by ore body count.

        Samples maps so each body-count class is equally represented:

        * ``n_orebodies=1`` — 50 % zero-body, 50 % one-body
        * ``n_orebodies=2`` — 33 % each of 0, 1, 2 bodies
        * ``n_orebodies=3`` — 25 % each of 0, 1, 2, 3 bodies

        Requires ``n_bodies_index.npy`` to exist in the pool directory
        (written automatically by ``generate_training_maps.py``).

        Parameters
        ----------
        n_orebodies
            Maximum number of ore bodies; must be 1, 2, or 3.

        Raises
        ------
        ValueError
            If the index file is missing, ``n_orebodies`` is out of range,
            or any required body-count class has too few maps.
        """
        if not isinstance(n_orebodies, int) or n_orebodies not in (1, 2, 3):
            raise ValueError(f"n_orebodies must be an integer 1, 2, or 3; got {n_orebodies!r}")

        index_path = self.path / "n_bodies_index.npy"
        if not index_path.exists():
            raise ValueError(
                f"n_bodies_index.npy not found in '{self.path}'. "
                "Regenerate the map pool with generate_training_maps.py."
            )

        body_index = np.load(index_path)  # shape (n_maps,) int8
        classes = list(range(n_orebodies + 1))  # [0] or [0,1] or [0,1,2] or [0,1,2,3]
        n_classes = len(classes)
        n_needed = n_train_maps + n_val_maps

        # maps per class, rounded so total >= n_needed
        per_class = int(np.ceil(n_needed / n_classes))

        rng = np.random.default_rng(seed)
        selected: list[int] = []
        for cls in classes:
            candidates = np.where(body_index == cls)[0].tolist()
            if len(candidates) < per_class:
                raise ValueError(
                    f"Not enough maps with {cls} ore bodies in pool "
                    f"(need {per_class}, have {len(candidates)}). "
                    "Generate more maps or reduce n_train_maps/n_val_maps."
                )
            chosen = rng.choice(candidates, size=per_class, replace=False).tolist()
            selected.extend(chosen)

        rng.shuffle(selected)
        selected = selected[:n_needed]  # trim any rounding excess

        train_indices = selected[:n_train_maps]
        val_indices = selected[n_train_maps:]
        return self.load_subset(train_indices), self.load_subset(val_indices)
