"""NPZ-based map pool for neural-belief training.

Maps are generated by ``generate_training_maps.py`` and stored in an npz pool
directory.  This module provides read-only access to that pool.

Directory layout
----------------
    <pool_dir>/
        config.pkl              dataset config written by the generation script
        map_00000.npz           per-map arrays (see below)
        map_00001.npz
        ...

Per-map npz keys
----------------
    boreholes     : (n_boreholes, V, D) float32 — raw (unstandardised) variables
    yield_target  : (n_x, n_y)         float32 — max-pooled yield field
    drill_locs    : (S, max_drills, 2) int16   — drill locations per sample
    drill_ore_vals: (S, max_drills)    float32 — ore values at drill locations
    drill_counts  : (S,)               int16   — valid drills per sample
    where S = samples_per_map
"""

from __future__ import annotations

import dataclasses
import pickle
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from .datasets import BeliefDatasetConfig

# ---------------------------------------------------------------------------
# Drill pattern helper
# ---------------------------------------------------------------------------


def _unpack_drill_patterns(
    locs: np.ndarray,
    vals: np.ndarray,
    counts: np.ndarray,
) -> list[tuple[list[tuple[int, int]], list[float]]]:
    samples = []
    for i, k in enumerate(counts):
        drill_locs = [(int(locs[i, j, 0]), int(locs[i, j, 1])) for j in range(k)]
        ore_vals = [float(vals[i, j]) for j in range(k)]
        samples.append((drill_locs, ore_vals))
    return samples


# ---------------------------------------------------------------------------
# Layer 1: In-memory container
# ---------------------------------------------------------------------------


@dataclass
class NpzMapCache:
    """In-memory container for map pool data loaded from an npz cache.

    Created by :meth:`NpzMapCacheStore.load_subset` and consumed by
    ``build_dataset_from_cache``.
    """

    borehole_arrays: list[np.ndarray]  # each (n_boreholes, V, D) float32, raw
    targets: list[np.ndarray]  # each (n_x, n_y) float32
    drill_patterns: list[list[tuple[list[tuple[int, int]], list[float]]]]
    cfg: BeliefDatasetConfig
    n_x: int
    n_y: int

    @property
    def pool_size(self) -> int:
        return len(self.borehole_arrays)


# ---------------------------------------------------------------------------
# Layer 2: NPZ persistence
# ---------------------------------------------------------------------------


class NpzMapCacheStore:
    """NPZ directory persistence for raw belief map pools.

    Each map is stored as a compressed npz file.  Global metadata
    (config) lives in the same directory.

    Parameters
    ----------
    path
        Directory that holds the pool files.
    """

    def __init__(self, path: Path | str) -> None:
        self.path = Path(path)

    def _map_path(self, idx: int) -> Path:
        return self.path / f"map_{idx:05d}.npz"

    def _config_path(self) -> Path:
        return self.path / "config.pkl"

    def count_maps(self) -> int:
        """Return the number of map files present on disk."""
        if not self.path.exists():
            return 0
        return sum(1 for p in self.path.glob("map_*.npz") if p.is_file())

    def load_subset(self, indices: list[int]) -> NpzMapCache:
        """Load the maps at *indices* and return an in-memory :class:`NpzMapCache`."""
        with open(self._config_path(), "rb") as f:
            meta = pickle.load(f)
        n_x: int = meta["n_x"]
        n_y: int = meta["n_y"]
        stored_cfg = BeliefDatasetConfig(
            n_maps=meta["n_maps"],
            samples_per_map=meta["samples_per_map"],
            min_drills=meta["min_drills"],
            max_drills=meta["max_drills"],
            seed=meta["seed"],
        )

        borehole_arrays, targets, drill_patterns = [], [], []
        for idx in indices:
            data = np.load(self._map_path(idx))
            borehole_arrays.append(data["boreholes"])
            targets.append(data["yield_target"])
            drill_patterns.append(
                _unpack_drill_patterns(
                    data["drill_locs"],
                    data["drill_ore_vals"],
                    data["drill_counts"],
                )
            )

        return NpzMapCache(
            borehole_arrays=borehole_arrays,
            targets=targets,
            drill_patterns=drill_patterns,
            cfg=dataclasses.replace(stored_cfg, n_maps=len(indices)),
            n_x=n_x,
            n_y=n_y,
        )

    def load_npz_data(
        self,
        n_train_maps: int,
        n_val_maps: int,
        n_orebodies: int,
        seed: int = 42,
    ) -> tuple[NpzMapCache, NpzMapCache]:
        """Load train/val subsets stratified by ore body count.

        Samples maps so each body-count class is equally represented:

        * ``n_orebodies=1`` — 50 % zero-body, 50 % one-body
        * ``n_orebodies=2`` — 33 % each of 0, 1, 2 bodies
        * ``n_orebodies=3`` — 25 % each of 0, 1, 2, 3 bodies

        Requires ``n_bodies_index.npy`` to exist in the pool directory
        (written automatically by ``generate_training_maps.py``).

        Raises
        ------
        ValueError
            If the index file is missing, ``n_orebodies`` is out of range,
            or any required body-count class has too few maps.
        """
        if n_orebodies not in (1, 2, 3):
            raise ValueError(f"n_orebodies must be 1, 2, or 3; got {n_orebodies}")

        index_path = self.path / "n_bodies_index.npy"
        if not index_path.exists():
            raise ValueError(
                f"n_bodies_index.npy not found in '{self.path}'. "
                "Regenerate the map pool with generate_training_maps.py."
            )

        body_index = np.load(index_path)  # shape (n_maps,) int8
        classes = list(range(n_orebodies + 1))  # [0] or [0,1] or [0,1,2] or [0,1,2,3]
        n_classes = len(classes)
        n_needed = n_train_maps + n_val_maps

        # maps per class, rounded so total >= n_needed
        per_class = int(np.ceil(n_needed / n_classes))

        rng = np.random.default_rng(seed)
        selected: list[int] = []
        for cls in classes:
            candidates = np.where(body_index == cls)[0].tolist()
            if len(candidates) < per_class:
                raise ValueError(
                    f"Not enough maps with {cls} ore bodies in pool "
                    f"(need {per_class}, have {len(candidates)}). "
                    "Generate more maps or reduce n_train_maps/n_val_maps."
                )
            chosen = rng.choice(candidates, size=per_class, replace=False).tolist()
            selected.extend(chosen)

        rng.shuffle(selected)
        selected = selected[:n_needed]  # trim any rounding excess

        train_indices = selected[:n_train_maps]
        val_indices = selected[n_train_maps:]
        return self.load_subset(train_indices), self.load_subset(val_indices)
